---
inverter:
  url: http://192.168.1.168:5000  # Inverter API url
  name: "Gen24-10.0"    # Inverter name (can be any string)
  device_id: 1
  metrics:
    - "CumulationInverterData"
    - "CommonInverterData"
    - "3PInverterData"
    # - "MeterRealtimeData"
    # - "PowerFlowRealtimeData"
record:
  influxdb_bucket: my-bucket      # InfluxDB bucket name
  request_interval: 3.0           # Request interval between different metrics in seconds (API has a request rate limit, up to 2 realtime requests are allowed to be performed in parallel with keeping a timeout of 4 seconds between two consecutive calls.)
  ignore_sunset: false            # Ignore sunset and even collect data when the sun is down.
location:
  name: "Greenwich"               # Location name (can be any string)
  region: "England"               # Location region (can be any string)
  timezone: "Europe/London"       # Location timezone
  latitude: 51.48                 # Location latitude,
  longitude: -0.00                # Location longitude
